package com.orsac.oiipcra.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class MasterData538Dto {

    private boolean is_active;
    private String agmt_value_approx_estimate_cost;
    private String agt_no;
    private String amount_required_for_election;
    private String ayacut_area_covered_in_area;
    private String balance_cost_as_on_12_2022_in_rs_lakh;
    private String bid_id;
    private String cad;
    private String cad2;
    private String cad_30_30;
    private String cad_40_40;
    private String canal;
    private String category;
    private String cluster;
    private String component_as_per_schematic;
    private String cost_per_ha_in_lakhs_rs;
    private String cost_per_hectare;
    private String cumulative_expenditure_by_12_2022_in_rs_lakh;
    private String date_of_commencement;
    private String date_of_election_of_pp;
    private String date_recieved;
    private String dpr_acceptable_or_not;
    private String drawings;
    private String ds_canal;
    private String ds_structures;
    private String estimated_amount;
    private String estimated_amount_including_gst;
    private String head_works_dam;
    private String head_works_earth_dam;
    private String head_works_hr;
    private String head_works_hr2;
    private String head_works_rip_rap;
    private String head_works_se;
    private String head_works_shutter;
    private String head_works_shutter2;
    private String head_works_structures;
    private String head_works_surplus;
    private String hw_distributi_on_system;
    private String hyd_data_nos_43;
    private String hyd_data_nos_54;
    private String hyd_data_nos_74;
    private String hyd_data_recieved_43;
    private String hyd_data_recieved_54;
    private String hyd_data_recieved_74;
    private String hydrological_assesment_done;
    private String hydrological_data_pending;
    private String if_drop_proposal_accepted;
    private String if_estimate_recieved;
    private String imp_of_approach_channel_to_tank;
    private String list_for_survey_of_reservior_counter_no;
    private String list_for_survey_of_reservior_counter_recieved;
    private String name_of_pp;
    private String no_of_pps_2;
    private String no_of_pps_for_which_voterlist_published;
    private String no_of_pps_which_election_completed;
    private String occ_dpr_recieved;
    private String ongoing_agreement_amount_with_gst;
    private String ongoing_projects_agreement_amount_with_gst;
    private String package_id;
    private String pp_remarks;
    private String present_cropping_khariff;
    private String present_cropping_rabi;
    private String president_of_pp;
    private String project_if_completed;
    private String project_proposed_to_be_dropped;
    private String proposed_cropping_khariff;
    private String proposed_cropping_rabi;
    private String publication_of_final_voter_list;
    private String remarks_fro_drop;
    private String reservoir_estimate_nos_45;
    private String reservoir_estimate_nos_54;
    private String reservoir_estimate_recieved_45;
    private String reservoir_estimate_recieved_54;
    private String river_basin;
    private String schematic_diagram;
    private String secretary_of_pp;
    private String sought_for_complaimce;
    private String status_of_pp;
    private String stipulated_date_of_completion;
    private String submission_of_estimates_nos_84;
    private String submission_of_estimates_recieved_84;
    private String surplus_escape_parameters_change_if_required_in_tbl;
    private String surplus_escape_parameters_existing_tbl;
    private String surplus_escape_parameters_existing_width_of_escape;
    private String surplus_escape_parameters_if_modification_required;
    private String surplus_escape_parameters_width_to_be_adopted;
    private String tanks_takenup_in_baseline_assessment_53;
    private String technical_sanction;
    private String technical_sanction_no_and_date;
    private String tender_premium;
    private String tender_prticipation_status;
    private String total_cost_of_package_in_rs;
    private String type;
    private String work_if_awarded;
    private Integer created_by;
    private Integer id;
    private String period_for_completion;
    private String project_id;
    private String updated_by;
    private String ca_khariff;
    private String ca_rabi;
    private String catchment_in_sq_km;
    private String command_area_delineated_ha;
    private String dcca_khariff_ha;
    private String dcca_rabi_ha;
    private String length_left_canal_km;
    private String length_right_canal_km;
    private String no_of_pps;
    private String no_of_pps_for_which_election_completed;
    private String percentage_filling_status_as_per_google_earth;
    private String rate_quoted;
    private String total_amount_for_dpr;
    private String unit_cost_per_ha_for_dpr;
    private Date created_on;
    private Date updated_on;
    private String tankName;
    private String districtName;
    private String blockName;
    private String divisionName;
    private Integer tankId;


    private Double tankWiseCatchmentArea;
    private Double tankWiseAyacutArea;
    private Double totalWaterSpreadArea;


}
